# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Build a Docker image

on:
  push:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        run: |
          docker --version
          docker build -t bla .
